# File: catppuccin_mocha_ansi.toml
[colors]
ansi = [
  "#45475a",
  "#f38ba8",
  "#a6e3a1",
  "#f9e2af",
  "#89b4fa",
  "#f5c2e7",
  "#94e2d5",
  "#a6adc8",
]
background = "#1e1e2e"
brights = [
  "#585b70",
  "#f37799",
  "#89d88b",
  "#ebd391",
  "#74a8fc",
  "#f2aede",
  "#6bd7ca",
  "#bac2de",
]
compose_cursor = "#f2cdcd"
cursor_bg = "#f5e0dc"
cursor_border = "#f5e0dc"
cursor_fg = "#1e1e2e"
foreground = "#cdd6f4"
scrollbar_thumb = "#585b70"
selection_bg = "#585b70"
selection_fg = "#cdd6f4"
split = "#6c7086"
visual_bell = "#313244"
bold = "#cdd6f4"
hyperlink = "#89dceb"

[colors.indexed]
16 = "#fab387"
17 = "#f5e0dc"

[colors.tab_bar]
background = "#11111b"
inactive_tab_edge = "#313244"

[colors.tab_bar.active_tab]
bg_color = "#cba6f7"
fg_color = "#11111b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#181825"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1e1e2e"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#313244"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#45475a"
fg_color = "#cdd6f4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
aliases = ["Catppuccin Mocha (Gogh)", "catppuccin-mocha"]
author = "Catppuccin Org"
name = "Catppuccin Mocha ANSI"
origin_url = "https://github.com/catppuccin/wezterm"
wezterm_version = "20220807-113146-c2fee766"
